### ISSUE TITLE
fd_forward.h: No such file or directory

### ISSUE THREAD

**Issue by wes1993** [xreef/beeprint_mks_esp32_camera_webserver#1]
Hello,
i'm trying to compile but i have this error:
fd_forward.h: No such file or directory
![image](https://user-images.githubusercontent.com/52070589/171911855-6df218f7-4ffa-4b64-8e8f-ef16e4533116.png)
Could you help me?

Best Regards
Stefano

**Comment by xreef** [comment]
Hi @wes1993,
It seems you have the wrong WiFiManager library.
Bye Renzo

**Comment by xreef** [comment]
The problem is that the face recognition package was removed from the 2.x.x version of esp32 core.
You must use 1.0.6.
Bye Renzo
