### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by spacemishka** [xreef/beeprint_mks_esp32_camera_webserver#2]
Hi there,
 i am getting this error.

`C:\Users\peter\AppData\Local\Temp\arduino_build_145815\sketch\esp32_cam_webserver.ino.cpp.o:(.literal._Z5setupv+0x68): undefined reference to `parseBytes(char const*, char, unsigned char*, int, int)'
C:\Users\peter\AppData\Local\Temp\arduino_build_145815\sketch\esp32_cam_webserver.ino.cpp.o: In function `setup()':
D:\tmp\esp32-cam_camera_webserver_enhanced\esp32_cam_webserver/esp32_cam_webserver.ino:188: undefined reference to `parseBytes(char const*, char, unsigned char*, int, int)'
`

I am using special characters like %, & in SSID or Password. Could this be the issue?

**Comment by xreef** [comment]
Hi @spacemishka,
try to cast value on parseBytesfunction, and check if the imports are correct.
Bye Renzo
